development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://:7dRAwvykb0iATc22yI2spUrb2KJbQ8Pp@redis-17177.c77.eu-west-1-1.ec2.cloud.redislabs.com:17177
  channel_prefix: dig-it_production
